project:
  type: website
  output-dir: docs

website:
  title: "Lucia Macakova"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: repos.qmd
        text: Portfolio
      



