project:
  type: website
  output-dir: docs

website:
  title: "My Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: repos.qmd
        text: Portfolio
      - href: https://luciamacakova.pythonanywhere.com
        text: Live App



